common:
  msg_source: 1                         # online Lidar
  send_packet_ros: false
  send_point_cloud_ros: true
lidar:
  - driver:
      lidar_type: RSAIRY
      msop_port: 6699
      difop_port: 7788
      imu_port: 6688
      user_layer_bytes: 0
      tail_layer_bytes: 0
      min_distance: 0.15
      max_distance: 60
      use_lidar_clock: false
      dense_points: false
      ts_first_point: true
      start_angle: 0
      end_angle: 360
      pcap_repeat: true
      pcap_rate: 1.0
      pcap_path: /home/robosense/lidar.pcap
    ros:
      ros_frame_id: rslidar_1
      ros_recv_packet_topic: /rslidar_packets_1
      ros_send_packet_topic: /rslidar_packets_1
      ros_send_imu_data_topic: /rslidar_imu_data_1
      ros_send_point_cloud_topic: /rslidar_points_1
      ros_queue_length: 100
